# Generated by Django 5.2.8 on 2025-11-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_seats', models.IntegerField()),
                ('seating_plan', models.TextField()),
                ('max_crew', models.IntegerField()),
                ('max_passengers', models.IntegerField()),
                ('standard_menu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=6, unique=True)),
                ('flight_datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_airline_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shared_flight_number', models.CharField(blank=True, max_length=6, null=True)),
                ('connecting_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_from', to='db.flight')),
                ('flight_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='db.airport')),
                ('flight_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='db.airport')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='db.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('seat_type', models.CharField(blank=True, choices=[('business', 'Business'), ('economy', 'Economy')], max_length=10, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('affiliated_passengers', models.ManyToManyField(blank=True, related_name='affiliated_with', to='db.passenger')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='db.flight')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infants', to='db.passenger')),
            ],
            options={
                'unique_together': {('flight', 'seat_number')},
            },
        ),
    ]
