# Generated by Django 5.2.7 on 2025-11-27 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='passenger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.UniqueConstraint(condition=models.Q(('seat_number__isnull', False)), fields=('flight', 'seat_number'), name='unique_seat_per_flight'),
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 3), models.Q(('age__lte', 2), ('parent__isnull', False)), _connector='OR'), name='infants_must_have_parent'),
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 3), models.Q(('age__lte', 2), ('seat_number__isnull', True)), _connector='OR'), name='infants_no_seat'),
        ),
    ]
