# Generated by Django 5.2.7 on 2025-11-01 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinAttendant',
            fields=[
                ('attendant_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('attendant_type', models.CharField(choices=[('CHIEF', 'Chief'), ('REGULAR', 'Regular'), ('CHEF', 'Chef')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cabin_attendants',
                'ordering': ['attendant_type', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('business_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('economy_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('min_pilots', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_pilots', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_cabin_crew', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_cabin_crew', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('standard_menu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DishRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('preparation_time', models.IntegerField(help_text='Preparation time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(limit_choices_to={'attendant_type': 'CHEF'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='crew_app.cabinattendant')),
            ],
            options={
                'db_table': 'dish_recipes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cabinattendant',
            name='known_languages',
            field=models.ManyToManyField(related_name='cabin_attendants', to='crew_app.language'),
        ),
        migrations.AddField(
            model_name='cabinattendant',
            name='allowed_vehicle_types',
            field=models.ManyToManyField(help_text='Which aircraft types this attendant can work on', related_name='cabin_attendants', to='crew_app.vehicletype'),
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(65)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('seniority_level', models.CharField(choices=[('SENIOR', 'Senior'), ('JUNIOR', 'Junior'), ('TRAINEE', 'Trainee')], max_length=10)),
                ('allowed_range', models.IntegerField(help_text='Maximum flight distance in km', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('known_languages', models.ManyToManyField(related_name='pilots', to='crew_app.language')),
                ('vehicle_type', models.ForeignKey(help_text='Which aircraft type this pilot can fly', on_delete=django.db.models.deletion.PROTECT, related_name='pilots', to='crew_app.vehicletype')),
            ],
            options={
                'db_table': 'pilots',
                'ordering': ['-seniority_level', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['seniority_level', 'is_active'], name='pilots_seniori_d16d75_idx'), models.Index(fields=['vehicle_type', 'is_active'], name='pilots_vehicle_66f511_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cabinattendant',
            index=models.Index(fields=['attendant_type', 'is_active'], name='cabin_atten_attenda_3deb07_idx'),
        ),
    ]
