# Generated by Django 5.2.8 on 2025-11-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('flight_date', models.DateTimeField(auto_now_add=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RosterPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_passenger_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=10)),
                ('is_infant', models.BooleanField(default=False)),
                ('related_passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.rosterpassenger')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='roster.roster')),
            ],
        ),
    ]
