# Generated by Django 5.2.8 on 2025-11-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('crew_type', models.CharField(choices=[('PILOT', 'Pilot'), ('CABIN', 'Cabin Crew')], max_length=10)),
                ('assigned_seat', models.CharField(blank=True, max_length=10, null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='roster.roster')),
            ],
        ),
    ]
